### ISSUE TITLE
使用grove-starter kit套件的问题

### ISSUE THREAD

**Issue by xmRichard** [01org/intel-iot-services-orchestration-layer#11]
你好，我们在使用iot-sol时遇到了一些困惑

目前的现状是，按照sol提供的教程进行了刷机、安装并且能够成功地通过putty进入iot-sol的界面上来，但是我们用的套件和sol教程中提到的startkit貌似不一样，所以连上了传感器也不清楚具体的pin值，好像就没办法用start_startkit.sh里面的预制服务来测试一下edison是否和iot-sol真正结合使用了。

目前有几个疑惑，希望能得到解答
1、start_grove.sh是提供给使用seeed的grove套件使用的吗？可是里面没有内置像start_startkit.sh里面的包含edison板及一些传感器的内容
2、如果没有给grove套件预设服务，是否都要自己根据具体情况具体传感器来编写，那么我应该在start_startkit.sh里添加服务还是在start_grove.sh里？因为那里好像已经有添加edison的hub了（我不知道自己理解有没问题）
3、昨天刚开始还能够连上localhost:8080，因为老显示usb无法识别设备（edison），所以我重启了电脑，之后usb可以读取到edison板了，但是我在putty上启动iot-sol之后，只能登陆localhost:3000，并不能登陆8080的端口，这是什么原因
4、我想在start_startkit.sh中测试传感器是否起作用，但是pin值好像一直输入不对，启动的时候却显示成功启动工作流，而停止的时候却会提示失败：workflow to stop in status loaded rather than enabled   这个是pin值错误造成的吗？
5、如果没有成功刷机，是不是在板子上启动iot-sol（想知道存不存在刷机不成功而导致之后进行不顺利的可能性）

我们组对于硬件的知识非常少，几乎都是小白入门阶段，磕磕绊绊地用edison还是挺不容易的，可能不少问题比较幼稚吧~如果能渡过初期，应该会好很多。谢谢！

**Comment by jiangzidong** [comment]
1, start_grove.sh是给seeed wio-link板的, 我认为你的用法是edison直接连接sensor, 那么不应该用这个脚本.
2, 现阶段没有专门针对seeed的grove套件的预设服务, 你需要自己编写添加. 
我建议在start_startkit.sh里添加服务, 因为很多服务都是类似的, 大部分gpio和aio相关的服务, 应该可以直接用startkit中的. 
如果你有arduino的经验, 那么凡是digitalread/write, analogread/write 能操作的sensor, startkit.sh都可以找到对应的服务.
3, 你在edison上启动iot-sol, 访问路径应该是<edison ip>:8080. 建议用start_startkit.sh 再试试. 之前出错可能是因为启动start_grove.sh, 而你并没有在config文件中配置好wio-link用户名密码等信息.
4, pin就是你的传感器插在edison哪个引脚上. 比如在gpio7上查了一个led灯, 那就是7. 比如在aio3上插了一个温度传感器, 那就是3. 请问你是运行哪一个service导致失败的? 
5, 你在板子上运行node -v, 如果是v0.12.0 或者 v4.4.4 就表示刷机成功. 如果不刷机, 是不能运行iot-sol的

**Comment by xmRichard** [comment]
感谢回复！基本解决了我的疑惑

我们目前使用的是seeed的grove套件，传感器也基本都是grove的，edison的引脚指的是那两排黑色的孔吧，grove的base shield就是整个插在那上面进行拓展的，而接传感器的口就会变成四针一口的杜邦线接口。
举个例子，比如上面的大接口D2（digital port）的四个针标注着GND、VCC、D3、D2；D3则是GND、VCC、D4、D3；还有A0是GND、VCC、A1、A0。现在我把传感器插到D2上，我应该如何确定它的PIN值呢？是2或者是3吗？

**Comment by jiangzidong** [comment]
我看了一下他们的说明 https://item.taobao.com/item.htm?spm=a1z10.1-c.w8432935-14644750657.17.0MJLWf&id=520233320144  
D2就对应的pin是2
A0就对应的pin是0

grove是否有需要两条数据线的sensor, 对于这类设备, startkit内置service是不支持的, 需要自己添加

**Comment by xmRichard** [comment]
谢谢解答！暂时没有用到两条数据线的sensor

目前还有一个奇怪的现象不知可否解答。
我们这个edison板子时不时连不了wifi，就是在putty窗口会出现failed to connect non-global ctrl_filename: (null) error: no such file or directory的提示，然后搜不到wifi，即使搜到，连接的时候也会弹出这个提示，然后过一会显示失败。

想请教一下这是为什么，而且好像有时可以连有时不可以连，是板子的问题吗？

**Comment by jiangzidong** [comment]
由于我没有遇到过类似问题, 所以不知道原因. 你可以去intel edison相关论坛上问问, 比如这个https://communities.intel.com/community/makers/edison/forums/content
