### ISSUE TITLE
有关edison board接口问题

### ISSUE THREAD

**Issue by KaboChueng** [01org/intel-iot-services-orchestration-layer#13]
您好！
请问edison board或arduino扩展板上有spi接口吗？我们买的LED灯带好像需要用到。

**Comment by jiangzidong** [comment]
有spi接口的

**Comment by KaboChueng** [comment]
您好！又来麻烦您了。
这次是iot的问题。重启之后，原来的工作流都没有了，hub也为空，没有控件。
请问有什么解决方案吗？重装iot，原来的工作流还在吗？

**Comment by jiangzidong** [comment]
你说的iot只是IoT SOL吗?
不管是SOL的重启, 还是Ediosn的重启, 都会保留原来的工作流. 他是存在node_modules/hope-demo/center/appbundle目录下的. 你可以检查一下该目录下是否有相应的信息.

你的现象, 连hub和service都没有了, 更像是SOL没有正确启动.

**Comment by KaboChueng** [comment]
您好，在相应的目录下可以找到两个工作流，但是在运行start_startkit.sh时候，这些工作流并没有被加载出来，而且hub是空的，如果是没有正确启动的话，应该如何解决呢？

**Comment by jiangzidong** [comment]
贴出 broker.log center.log 和 startkit_hub.log 这三个文件的内容.
他们是运行IoT SOL时的日志文件

**Comment by KaboChueng** [comment]
您好，这三个文件要怎么打开呢？

**Comment by jiangzidong** [comment]
就在IoT SOL的主目录下, 直接用vi打开或者任意编辑器.

**Comment by KaboChueng** [comment]
broker.log
![broker log_1](https://cloud.githubusercontent.com/assets/18261984/17275386/549e3470-5738-11e6-8d77-104fa7e156c5.png)
![broker log_2](https://cloud.githubusercontent.com/assets/18261984/17275388/59370b7e-5738-11e6-9365-fb5b9d4a5009.png)

# ![broker log_3](https://cloud.githubusercontent.com/assets/18261984/17275389/5cc4399c-5738-11e6-9b0f-c4b5841b242c.png)

center.log

# ![center log](https://cloud.githubusercontent.com/assets/18261984/17275391/73a216c0-5738-11e6-95ef-b4154204872d.png)

startkit.log
![startkit_1](https://cloud.githubusercontent.com/assets/18261984/17275392/7c359640-5738-11e6-83ba-39a16c072f0b.png)
![startkit_2](https://cloud.githubusercontent.com/assets/18261984/17275394/89e713cc-5738-11e6-8a70-36e4125eceda.png)

**Comment by jiangzidong** [comment]
这个错误是某个json文件语法错误, 导致启动失败

你是不是增加了什么service 或者hub? 对某个json文件手动进行了修改?

**Comment by KaboChueng** [comment]
是的，增加了一个service，启动以后没反应，接着edison 就自动重启了，之后就打不开了。

**Comment by jiangzidong** [comment]
增加的service在 node_modules/demo/xxx(你的hub名字)/thing_bundle/yyy(thing name)/   下面
你贴一下对应的service.json (最好不要截图, 而是把内容放上来)

如果thing也是自己创建的, 把thing.json也放上来

**Comment by KaboChueng** [comment]
您好，我找到那个目录发现导致错误的service中的代码没有保存下来，是空的，但是其他的代码还在，所以我们决定把代码拷出来，重装iot。
真的很谢谢您的帮助！
