### ISSUE TITLE
iot SOL里面不可以让多个服务同时运行，请问该如何正确使用呢？

### ISSUE THREAD

**Issue by dejianwei** [01org/intel-iot-services-orchestration-layer#14]
我测试发现在iot SOL里面不可以让多个服务同时运行。一开始我们是准备用iot SOL来写所有的代码，我们需要控制小车的前进，超声波测距，RFID模块读取等等，但是测试发现， 比如我有一个服务是控制步进电机前进的，然后另一个服务是超声波测距的，这两个服务需要同时运行，即多线程，但是在iot SOL里面，一旦一个服务在运行，那么就算另一个服务有输入，但是也不会启动服务的kernal.js，一直等到上一个服务结束了才可以运行。因此对于我们这种需要多线程的项目，如何正确的使用这个iot SOL平台呢？

另外发现一旦一个服务陷入while循环，服务不停止，那么就无法关闭工作流，只有服务正常停止了才可以关闭工作流。这时候我采用的办法是在命令行下重新 `node  start_startkit.js`， 有什么更优雅的解决办法吗？

提前说声谢谢！

**Comment by jiangzidong** [comment]
因为在nodejs的机制下, 所有js代码是运行在一个线程里面的, 并不支持js的多线程. 所以如果你的某一个kernal.js中有阻塞的代码, 比如while(1), 就会导致整个工作流都停止.

可能的解决办法有1), 将你的代码换成非阻塞的, 比如setTimeout, setInterval, 2)kernal.js中另外开一个进程, child-process来处理, 注意这种情况下需要做好进程间通信的工作

**Comment by dejianwei** [comment]
恩恩，谢谢 : D
