### ISSUE TITLE
关于edison board I2C端口

### ISSUE THREAD

**Issue by KaboChueng** [01org/intel-iot-services-orchestration-layer#17]
您好！
   我们买了9轴姿态传感器，通过I2C方式连接，但是connection failed。我们怀疑是不是I2C端口坏了，请问有什么方法检测一下吗？

**Comment by KaboChueng** [comment]
您好！
我们尝试使用spi接口连接，arduino扩展板上有时钟、输入和输出端口，缺少一个片选信号端口。
是我们搞错了吗？

**Comment by jiangzidong** [comment]
SPI SS端口是pin10 请参考 http://www.intel.com/content/www/us/en/support/boards-and-kits/000005583.html

**Comment by w3jc** [comment]
spi的使能和片选是可以调整的，选择其余数字接口应该都可以。
