### ISSUE TITLE
关于服务器的问题

### ISSUE THREAD

**Issue by windmillknight** [01org/intel-iot-services-orchestration-layer#18]
您好！
      请问我该怎么样把我的网页放到iot-sol的服务器上去呀？

**Comment by jiangzidong** [comment]
hi 能否更具体的描述一下你要做什么

**Comment by windmillknight** [comment]
额，我做了一个3d模型的网页，想把它放到服务器上，让我能够通过192.168.1.xx/我的网页，访问它，然后我想的iot-sol本身有服务器，如果我再自己用node 搭个服务器挺奇怪的，所以就想放在iot-sol的服务器上。

**Comment by jjykh** [comment]
是静态网页吗？如果是的话，简单修改IoT SOL中ui-dev和center的代码，应该就可以配置出一个静态路由，请参考 hub-center-shared/lib/config.js 和  ui-dev/ui/js/components/nav_bar/nav_bar.x.js

**Comment by windmillknight** [comment]
您好，您说的是dev版本么，我用的是master，里面没有ui-dev/ui这个文件夹

**Comment by windmillknight** [comment]
您好,
    请问 web_socket: true 这个属性的作用是什么？

**Comment by jjykh** [comment]
你好，
1) 修改ui相关的代码，需要切换到dev分支进行。
2) web_socket 选项控制服务器是否开启WebSocket中间件，目前这个选项必须开启。

**Comment by windmillknight** [comment]
您好！
       是只需要自己写一个类似于
      /home/huahua/图片/屏幕截图.png
       这样的代码就可以了么

**Comment by windmillknight** [comment]
您好！
   是只需要写一个类似
         user_web_app: {
      $type: "WebApp",
      $params: {
        port: _.get(this.json, "web_for_end_users.port", 3000),
        static: [absdir + "/ui-user/public", absdir + "/ui-widgets"],
        web_socket: true
      }
    },
这样的代码就可以了么?

**Comment by jjykh** [comment]
你好，说实话我还不太清楚你想要实现什么样的功能。如果仅仅是准备托管一组静态页面，那么只需要将路径加到上面的 static 中，应该就可以了。

**Comment by windmillknight** [comment]
明白了！谢谢您
