### ISSUE TITLE
IoT 可以与其他的程序共同运行吗

### ISSUE THREAD

**Issue by jackieliu-52** [01org/intel-iot-services-orchestration-layer#19]
因为node*js好像不能做到微细的控制，所以我想问一下，能在运行iot的程序的同时运行arduino所编写的程序吗

**Comment by w3jc** [comment]
我也是打算一起运行，应该是可以的因为两个平台的是独立运行的。

**Comment by jiangzidong** [comment]
hi
原则上是可以并行的. iotsol的service可以开子进程, 该进程运行arduino程序即可

但是要注意, arduino程序本身初始化时, 会初始化整个edison board接口.
 如果此时你的工作流的其他部分是和edison 硬件接口相关的, 那么调用arduino程序会导致这些模块失效

**Comment by w3jc** [comment]
如果arduino程序不作为子进程呢？有点搞不太懂。或者要是在arduino中初始化了sol中服务要用到引脚是不是就可以正常使用了？比如我要在sol中读模拟输入，是不是就不用在arduino里初始化了？而我要在sol里数字输出，就得在arduino里把相应的引脚初始化？

**Comment by jiangzidong** [comment]
你可以试试
 Arduino的初始化是在调用你的setup()之前的
这个初始化的过程会与mraa产生冲突

**Comment by w3jc** [comment]
我又想了一下应该是spi的问题，因为我用了硬件spi做通信，而板子上的模数转换芯片也是用的spi。数字输出好像不受影响。

**Comment by jackieliu-52** [comment]
会跟mraa产生冲突吗？那就是说和硬件有关的所有操作必须给arduino来做了.....

**Comment by w3jc** [comment]
今天又查了一下发现模数转换芯片用的spi和引出的spi引脚不一样，是我的模数转换电压基准的跳线跳错了。刚才也测试了一下，在arduino程序运行的同时仍然可以通过sol来控制硬件，模拟和数字都不影响。
