### ISSUE TITLE
 some node packages are omissive

### ISSUE THREAD

**Issue by callblueday** [01org/intel-iot-services-orchestration-layer#2]
when I compile the source,  I foudn some node packages are omissive, and it really spend a lot time for me to fix them. I write a list:

`message/package.json`

update:

```
"dependencies" : {
    "socket.io": "^1.3.7"
}
```

add:

```
"dependencies" : {
    "engine.io": "^1.5.4",
    "socket.io-client": "^1.3.7",
    "socket.io-parser": "^2.2.5"
}
```

`ui-dev/bower.json`

update:

```
"socket.io-client": "~1.3.7"
```

`ui-dev/package.json`

update:

```
"dependencies" : {
    "socket.io": "^1.3.7",
    "socket.io-client": "^1.3.7",
}
"devDependencies" : {
    "gulp-useref": "~3.0.2",
    "gulp-util": "~3.0.7",
}
```

add:

```
"dependencies" : {
    "wrappy": "~1.0.1",
    "glob": "~6.0.1",
    "minimatch": "~3.0.0"
}
"devDependencies": {
    "end-of-stream": "^1.1.0",
    "nodes": "~0.1.0",
    "readable-stream": "~2.0.4",
    "xtend": "~4.0.1"
}
```

`ui-user/package.json`

add:

```
"devDependencies" : {
    "core-util-is": "~1.0.2",
    "isarray": "~0.0.1"
}
```

`ui-widgets/package.json`

add:

```
"devDependencies" : {
    "to-fast-properties": "~1.0.1",
    "esutils": "~2.0.2",
    "repeating": "~2.0.0",
    "globals": "~8.12.0",
    "line-numbers": "~0.2.0",
    "js-tokens": "~1.0.2",
    "chalk": "~1.1.1",
    "babylon": "~6.2.0",
    "convert-source-map": "~1.1.2",
    "minimatch": "~3.0.0",
    "slash": "~1.0.0",
    "path-exists": "~2.1.0",
    "json5": "~0.4.0",
    "path-is-absolute": "~1.0.0",
    "shebang-regex": "~1.0.0",
    "source-map": "~0.5.3",
    "detect-indent": "~4.0.0",
    "trim-right": "~1.0.1",
    "is-integer": "~1.0.6",
    "try-resolve": "~1.0.1",
    "debug": "~2.2.0",
    "babel-plugin-constant-folding": "~1.0.1",
    "babel-plugin-eval": "~1.0.1",
    "babel-plugin-remove-debugger": "~1.0.1",
    "babel-plugin-remove-console": "~1.0.1",
    "babel-plugin-inline-environment-variables": "~1.0.1",
    "babel-plugin-dead-code-elimination": "~1.0.2",
    "babel-plugin-react-display-name": "~2.0.0",
    "babel-plugin-undeclared-variables-check": "~6.1.18",
    "babel-plugin-react-constant-elements": "~1.0.3",
    "regexpu": "~1.3.0",
    "babel-plugin-proto-to-assign": "~1.0.4",
    "babel-plugin-undefined-to-void": "~1.1.6",
    "regenerator": "~0.8.42",
    "babel-plugin-runtime": "~1.0.7",
    "babel-plugin-member-expression-literals": "~1.0.1",
    "babel-plugin-property-literals": "~1.0.1",
    "babel-plugin-jscript": "~1.0.4"
}
```

the gulp file also reports error, i fix it like that, it work.

`ui-dev/gulpfile.js`

```
// var assets = $.useref.assets({searchPath: [".tmp", "ui"]});
var assets = $.useref({searchPath: [".tmp", "ui"]});
```

has anyone else these same problems? I have made a fork with the fixed version.  https://github.com/callblueday/intel-iot-services-orchestration-layer

**Comment by jonathanding** [comment]
Hi callblueday,

Would you kindly please provide your environment (OS and node.js version) and steps so that I could try to reproduce this?

I just tried on my Ubuntu with node.js 0.12, and didn't encounter this issue. Actually a lot of packages you added aren't directly used by us. They seem to be next level dependencies of the packages we used. For example, we may use package X, but X uses Y. But we don't directly use Y actually and no need to add in package.json

I suspected that maybe when `npm install X` in your environment, it failed to automatically install Y while it should. As the result, you would see error of missing Y. While adding Y to package.json would workaround this (doing so installs Y at top level rather than node_moudles of X), it isn't the issue of package.json and we shouldn't do this fix.

These are steps I did on my Ubuntu trying to reproduce:

``` shell
  # get a clean code
  git clone http://..........
  cd ...
  # clean local npm caches to ensure I download caches from remote
  npm cache clear
  # build
  ./link-npms.sh
  ./build.sh
 # try
  cd dist
  ./start_mock_demo.sh

 # and then http://localhost:8080 in a browser
```

**Comment by callblueday** [comment]
Thanks, @jonathanding . The OS is Mac OSX Yosemite 10.10.5,  and my node version is v0.12.2.
I'll try it again in other os, thanks a lot for your reply!

**Comment by jonathanding** [comment]
Thanks callblueday. Please also help dump the stdin and stderr to a file if you continue to see this issue. This would help a lot for my diagnose :)

**Comment by callblueday** [comment]
OK!
