### ISSUE TITLE
IOT平台与可运行程序的链接问题

### ISSUE THREAD

**Issue by sunpeng1996** [01org/intel-iot-services-orchestration-layer#21]
有一个问题请教，我们已经建立好了可运行的Java程序，并且放置到英特尔的板子上，也把我们的IOT平台装在了板子上，请问如何把我们的程序封装成服务运行在IOT平台上？谢谢，期待您们的回复。换句话说，讲我们写好的Java程序放在iot平台上，使得在IOT平台上看到工作流。

**Comment by jiangzidong** [comment]
需要自己创建一个service, 然后里面开一个子进程来运行java. 
详见[这里](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service/5-service with binary)

**Comment by sunpeng1996** [comment]
谢谢您
