### ISSUE TITLE
在使用SerialPort时，node提示SerialPort错误，无法正常使用。

### ISSUE THREAD

**Issue by umarufans** [01org/intel-iot-services-orchestration-layer#22]
收到如下错误信息：
DEPRECATION: Please use `require('serialport')` instead of `require('serialport').SerialPort`s

请问如何解决

**Comment by jiangzidong** [comment]
请问是在使用哪个service的时候报错了?

**Comment by umarufans** [comment]
谢谢您的回复！是使用nodered里的serial in 或者 serial out，在程序启动时终端收到的错误提示。

**Comment by jjykh** [comment]
请问你使用的是什么版本？Node.js 和 IoT SOL的，我们最近发布了 v2.0.

**Comment by umarufans** [comment]
Node.js版本4.4.2 IoT SOL版本2.0 是前几天刚更新的。（之前版本的Layer没有找到Serial in/out。）

**Comment by jjykh** [comment]
另外，OS是什么平台的呢？

**Comment by umarufans** [comment]
Edison Board的OS使用的是官方提供的最新版本的Yotco，Host OS使用的是 OS X 10.11

**Comment by imcort** [comment]
请问一下，新版iot-sol里面加入的nodered有测试过吗？感觉不太好用

**Comment by jiangzidong** [comment]
@lcx960324 你好, 我想再确认一下, 你用的SOL版本是2.0.0还是2.0.1, 这个信息在package.json中可以查到

**Comment by umarufans** [comment]
npm version: 2.15.1
node version: 4.4.3
iot-sol version: 2.0.1

**Comment by jjykh** [comment]
非常感谢您反馈的信息！这个BUG已经确认并已在v2.0.2版本中修复，请知悉！

**Comment by umarufans** [comment]
O(∩_∩)O谢谢！
