### ISSUE TITLE
用户自定义服务出现问题

### ISSUE THREAD

**Issue by sunpeng1996** [01org/intel-iot-services-orchestration-layer#24]
var out = Math.abs(IN.input);
console.log("abs",IN.input);
sendOUT({
    value:out
});

您好，我这样写一个service，但是并没有任何log输出，也不知道它是否正确运行。请问log在哪里看到呢？

**Comment by jiangzidong** [comment]
因为我们启动脚本 比如start startkit. sh 将输出重定向到了文件中 所以在log文件中 比如startkithub.log
