### ISSUE TITLE
在使用SerialPort时候，出现错误提示 Error Resource temporarily unavailable Cannot lock port

### ISSUE THREAD

**Issue by imcort** [01org/intel-iot-services-orchestration-layer#25]
刚刚更新了2.0.2版iot-sol，

在终端中使用echo “example” > /dev/ttyUSB0 是可以输出的，但是使用iot-sol的nodered里的serial out时，一启动程序，终端里就报错：Serial.errors.error { port: '/dev/ttyUSB0',
  error: 'Error: Error Resource temporarily unavailable Cannot lock port' }，不知为什么

**Comment by jiangzidong** [comment]
1, 你是不是同时有其他程序也在使用串口. 请详细描述一下你的使用场景
2, 需要root权限

**Comment by imcort** [comment]
edison板登录时是使用的root账户，板子上只装了iot-sol，串口即使在点击运行的时候有报错，有时也能正常使用。我需要使用串口和arduino板子通信，edison上的usb host端口接入了一个pl2303芯片

**Comment by imcort** [comment]
@jiangzidong 我试着在Mac上使用serial in和serial out这个service，依旧报同样的错

**Comment by jiangzidong** [comment]
是的, 我们发现了里面的bug, 已经修复并上传了, 请用最新版本试试. 非常感谢!

**Comment by imcort** [comment]
更新版本后问题已解决，非常感谢!
