### ISSUE TITLE
在使用Layer的Add Service功能时，无法正常下载npm依赖

### ISSUE THREAD

**Issue by umarufans** [01org/intel-iot-services-orchestration-layer#27]
根据官方教程进行自定义http_request service编写，教程本地地址如下（Layer运行在OSX系统环境下） http://localhost:8080/app-dev/#getstarted/example/add_http_request，进行到step4: install service's dependencies的时候，出现如下错误：

Failed to install_package$ for HOPE_SERVICE_672f2870_79c9_11e6_9720_abbc39252740 with error: TypeError: Cannot read property 'length' of undefined.

运行环境信息：
System: Mac OS X 10.11.6
npm version: 3.10.7
node version: 4.5.0
layer version: 2.0.3

**Comment by jayjliang** [comment]
你好,从目前你贴的信息来看,不能看到原因在哪里,可以把完整的堆栈信息放上来吗,谢谢~

**Comment by umarufans** [comment]
更换网络后问题解决，可能是之前的网络对npm服务器的访问有限制，谢谢您！
