### ISSUE TITLE
在使用阿里大于短信平台service时，出现错误

### ISSUE THREAD

**Issue by imcort** [01org/intel-iot-services-orchestration-layer#29]
具体表现为无法发送短信，center.log中有如下提示

> > > > > Unhandled Exception >>>>>>
> > > > > TypeError: Cannot read property 'IN_id' of undefined
> > > > >     at Node.send (/Users/ZiyueWu/Documents/node_modules/iot-sol/node_modules/hope-workflow/lib/node.js:442:16)
> > > > >     at /Users/ZiyueWu/Documents/node_modules/iot-sol/node_modules/hope-workflow/lib/in_port.js:110:17

**Comment by umarufans** [comment]
同问 相同的错误 一脸懵逼= =

**Comment by jayjliang** [comment]
请问你们是在什么情况下出现这个问题的呢 能否把你们的workflow贴出来 截个图

**Comment by jiangzidong** [comment]
@imcort @lcx960324  请提供更详细的信息, 比如工作流截图以及操作步骤, 来帮助我们定位和分析

**Comment by imcort** [comment]
非常简单的流，只为测试阿里大于
![2016-09-24 10 25 13](https://cloud.githubusercontent.com/assets/18713720/18809075/dc9ecdd8-82a5-11e6-8af4-06511e8150c3.png)

**Comment by jayjliang** [comment]
这个问题是因为你的sms_param有问题,在报错信息里,你往上看,会有提示
SyntaxError: Unexpected token l in JSON at position 1
                      at Object.parse (native)
                      at Object.service_shared.sms (/home/user/ssg_iotwebruntime-js-iot/center/lib/hubbundles/thingbundle/life/alidayu_sms__start:36:20)
                      at /home/user/ssg_iotwebruntime-js-iot/center/lib/hubbundles/thingbundle/life/alidayu_sms__kernel:3:17
                      at run_func (/home/user/ssg_iotwebruntime-js-iot/session-manager/lib/session-manager.js:486:7)
                      at /home/user/ssg_iotwebruntime-js-iot/session-manager/lib/session-manager.js:312:5
                      at SessionManager.invoke_session$ (/home/user/ssg_iotwebruntime-js-iot/session-manager/lib/session-manager.js:303:10)
                      at main_invoke (/home/user/ssg_iotwebruntime-js-iot/session-manager/lib/session-manager.js:94:21) {
                    id: "NODE_68f1aad0-844f-11e6-9267-09c727adc7d9",
                    service: "alidayu_sms@/home/user/ssg_iotwebruntime-js-iot/center/lib/hubbundles/thingbundle/life@112eac7b0a406aec1ac57824fa93ec85__built_in_hub__",
                    status: "sending",
                    shared: {},
                    **nodered: {},
                    is_status_stable: true,
                    mnode: "112eac7b0a406aec1ac57824fa93ec85__mnode**",
                    config: {
                      app_key: "1",
                      sms_free_sign_name: "1",
                      sms_template_code: "1",
                      secret: "1"
                    }
                  }
类似与这样的 这才是真正的错误愿意
正确解决方法为sms_param为
{"location":"B623","time":"2016-9-14 14:256-1-1","message":"燃气异常"}
你改成这样试试

**Comment by jayjliang** [comment]
这种错误在右侧面板也可以看到的
