### ISSUE TITLE
蓝牙数据传输

### ISSUE THREAD

**Issue by Grassgod** [01org/intel-iot-services-orchestration-layer#31]
尝试将一个node版本的蓝牙通讯服务代码改写成IOT的一个服务
代码如下：
start.js:
var m = require('mraa'); //require mraa
console.log('MRAA Version: ' + m.getVersion());
u = new m.Uart(0);
done();
kernel.js:
function sleep(delay) {
  delay += new Date().getTime();
  while (new Date() < delay) { }
}

//配置BLE
u.setBaudRate(115200);
u.setMode(8, 0, 1);
u.setFlowcontrol(false, false);
sleep(200);

while (true){
  //等待下一个信号
  sleep(1000);
  var a = u.readStr(4);
  switch(a){
   //判断代码
  }
  sleep(1000);
}
服务一直在u.setBaudRate(115200);报错 请问有解决办法么

**Comment by jiangzidong** [comment]
start.js 和 kernel.js 之间不直接共享数据. start中的u, 在后面是访问不到的

写service之前请详细看一下这个[说明](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service/2-service)

对于你的例子, 
`shared.u = new m.Uart(0);`

之后访问u 都用`shared.u`, 然后再试试
