### ISSUE TITLE
dfrobot也消失了

### ISSUE THREAD

**Issue by w3jc** [01org/intel-iot-services-orchestration-layer#32]
上次是Builtin消失，这次是dfrobot消失，包括自己写的服务也都不见了，上次说的清除所有文件夹后还是没有dfrobot。只能说很失望，所有东西都要从头做起了。

**Comment by w3jc** [comment]
重新安装了新版的sol不知道有没有改善。新增加的一些内置服务能否使其作为服务器处理http的get请求？

**Comment by jiangzidong** [comment]
@w3jc 你好, 我们还是不能重现"消失"的问题.
- 能否告诉我们重现的方法, 以及center.log, startkothub.log 里面的内容
- #16 里面已经讲述了工作流和你的自定义服务保存的地址, 如果出了问题, 也请把里面的内容贴出来看看 (我怀疑是自定义服务的格式错误)
- 新添加了一些[network相关服务](http://01org.github.io/intel-iot-services-orchestration-layer/#reference/builtin/Network/http_request) : 暂时没有http_server的功能, 有tcp_server. 建议你可以自己实现一个, 并十分鼓励你提交PR
