### ISSUE TITLE
iot-sol有变量吗？我想暂存一个数据怎么办？

### ISSUE THREAD

**Issue by imcort** [01org/intel-iot-services-orchestration-layer#33]
用读写文件的方法好像很慢

**Comment by jiangzidong** [comment]
http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service/2-service

有3种不同程度的共享
shared: 同一个服务实体(session)的不同阶段(start, kernel, resume, ...)之间共享
service_shared:同一个服务的不同实体之间共享
hub_shared:同一个hub的所有服务之间共享

IoT SOL 暂时还不提供整个IoT系统(不同hub之间)共享的字段. 如果你是这种需求, 完全可以自己实现一个service, 最简单的实现方式: 该service内部就是一个hash map
