### ISSUE TITLE
关于pull request

### ISSUE THREAD

**Issue by anonymous530** [01org/intel-iot-services-orchestration-layer#37]
你好，我想问下，如果要添加新模块，上传的时候，是新增文件夹，还是在哪个文件夹里直接上传？如果是新增文件夹，在哪个目录下新建？文件夹名字是new_things_by_user，还是要指定文件名？  
     In conclusion, 我们新增模块该如何上传？

**Comment by jiangzidong** [comment]
你好, 你是想将自己写的thing/services 作为PR merge到IoT SOL中对吗?

这个取决于新模块的内容, 你能简单介绍一下是一个什么模块吗.

**Comment by anonymous530** [comment]
你好，这个模块是关于mysql数据库相关的增删改查以及建表删表之类的

**Comment by jiangzidong** [comment]
你好, 数据库相关的操作是一种通用的服务(与平台/硬件无关), 我建议可以作为内置服务
- 请针对dev branch 提交PR, 而不是master branch
- 现有的内置服务在https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/center/lib/hubbundles/thingbundle, 请仿造其中的例子, 添加相应的thing文件夹和service文件夹即可

期待你的PR

**Comment by anonymous530** [comment]
Thanks

**Comment by 2659494286** [comment]
你好，我们也想添加一个利用ajax 发送异步请求，以及I2c，uart这些通讯协议相关的模块，请问这个有需要么

**Comment by 2659494286** [comment]
作为内置服务

**Comment by jiangzidong** [comment]
@2659494286 nodejs本身就可以通过http模块 或者 request 模块 来实现restful api的异步通信, 我们已经封装了相关service, 比如 http://01org.github.io/intel-iot-services-orchestration-layer/#reference/builtin/Network/http_request

请问你想添加的ajax功能是否会和上面的重复?

**Comment by 2659494286** [comment]
这个我再研究一下，看看会不会重复。另外，像I2c ，UART这种硬件相关的通讯模块有需要么

**Comment by 2659494286** [comment]
@jiangzidong

**Comment by jiangzidong** [comment]
I2C, UART这类服务是与平台相关的, 现阶段请仿造https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/demo 中的startkit 或者edison 新建一个hub, 将这些service加入其中

之后我们会refactor 目录结构, 专门会有thing_lib目录,并在hub启动时选择加载的thing, 这样第三方的thing/service都可以放到thing_lib中, 按需加载.

**Comment by 2659494286** [comment]
@jiangzidong   哦哦，好的。刚看了下，我的这个ajax是基于XMLHttpRequest 的，不知道和内置的 http request 有没有区别

**Comment by jiangzidong** [comment]
这和用什么实现的关系不大, 主要是看你想提供的服务是什么.

内置http_request提供的服务是 get post put delete这样的http 请求.

**Comment by anonymous530** [comment]
你好，那请问如果添加新模块，那我们需要自己编写模块对应的doc/html吗？

**Comment by anonymous530** [comment]
另外，需要单元测试吗？

**Comment by jiangzidong** [comment]
文档的位置在 https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/doc/md/
如果是对buitin hub 增加模块, 就对应buitin目录.

你可以先提交代码, 并在PR中解释该模块的作用. 
等到我们review后再增加相关文档

**Comment by anonymous530** [comment]
好的，那解释模块作用的文档是单独写吗？ 存放目录是什么呢？
在2016年09月30日 08:04，Zidong Jiang 写道:

文档的位置在 https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/doc/md/
如果是对buitin hub 增加模块, 就对应buitin目录.

你可以先提交代码, 并在PR中解释该模块的作用.
等到我们review后再增加相关文档

**Comment by jiangzidong** [comment]
文档的目录就在https://github.com/01org/intel-iot-services-orchestration-layer/tree/dev/doc/md/
请参考其他模块的形式来写

**Comment by sunpeng1996** [comment]
请问如果我们想为IOT增加 ： 语音转文字 和 文字转语音 的服务，请问可以么？是否符合IOT Layer的需要？
