### ISSUE TITLE
中文字符的传递

### ISSUE THREAD

**Issue by sunpeng1996** [01org/intel-iot-services-orchestration-layer#39]
您好，我在IOT里创建了一个服务，其中该服务的输出为中文的字符串，然后连接到下一个服务的输入，可是发现到这个输入时，输入的内容不是中文字符串，而是一个类型为buffer的整型数组，请问怎么能让该服务的输入和上一个服务的输出变成一样的呢？

**Comment by jiangzidong** [comment]
@sunpeng1996 我并不能重现这个问题, 我这里可以正常传递中文字符串.
请把你的具体流程贴出来, 主要是"输出的语句"和"你是如何判断输入内容的"

![image](https://cloud.githubusercontent.com/assets/15059452/19064370/8ed757a4-8a3f-11e6-8365-03a6e4d5a460.png)

**Comment by sunpeng1996** [comment]
您好，感谢您的回复：
我们的结构是：[http://t3.qpic.cn/mblogpic/02c7fe5003d12d33f4e2/80](url) 

前一个服务的kernel代码为： [http://t3.qpic.cn/mblogpic/e7ed50aa15cff9464ffe/120](url)

后一个服务直接接受前一个服务的输出，kernel代码为：[http://t3.qpic.cn/mblogpic/77a34b6705ebc58b1b76/320](url)

实际上前一个服务是调用java可执行程序，我们通过stdout输出的是java程序中system.out.println(“”)的内容，我们想接受java程序生成的（也就是print）的中文字符，可是到了下一个服务，就变成了整型数组。谢谢，期待您的回复。

**Comment by sunpeng1996** [comment]
抱歉，好像图片看不了。
[更新图片地址：](http://t.qq.com/p/t/516672081889938?pgv_ref=copyShare)
第一个服务的代码：
`//获取到创建进程的方法
const spawn = require('child_process').spawn;
const ls = spawn('java', ['-jar', '/home/pi/Desktop/EyeLife1.jar']);

ls.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
  sendOUT({
        out1:data
    });
});

ls.stderr.on('data', (data) => {
  console.log(`stderr: ${data}`);
});

ls.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
});
`

第二个服务的kernel代码：
console.log("testForEyeLife:", IN.input);

**Comment by jiangzidong** [comment]
因为stdout的数据就是buffer
你应该用toString()转化为string类型, 然后再sendOUT

console.log(stdout: ${data}); 这里自动转化了, 所以你以为输出的是string. 如果你改为console.log(data) ,  就能看出不同了

**Comment by sunpeng1996** [comment]
好的，非常感谢。O(∩_∩)O
