### ISSUE TITLE
如果要用自己的板子来运行项目的话应该怎么配置呢？

### ISSUE THREAD

**Issue by richardcypher** [01org/intel-iot-services-orchestration-layer#4]

**Comment by ruizeng** [comment]
你的板子能跑nodejs即可

**Comment by richardcypher** [comment]
@ruizeng 就是随便什么板子，不是edison的也可以，在上面跑run hub就行了吗？

**Comment by ruizeng** [comment]
@richardcypher 不是随便什么板子，需要性能比较好点如树莓派，关键是能运行nodejs环境。不过用官方的edison肯定是最方便的，我是用edison跑的。

**Comment by richardcypher** [comment]
@ruizeng ，就是比如树莓派的板子然后有nodejs，然后运行的时候`run hub`，应该就可以了吧？

**Comment by jonathanding** [comment]
是的，只要能跑node.js即可。另外如果板子上面有传感器等的话，需要能够通过javascript访问它。在Edison上我们是通过libmraa直接访问那些analog和digital的arduino pin的

Thanks,
Jonathan

**Comment by jiangzidong** [comment]
补充一下，如果已经有了访问外设的可执行程序A，可以直接利用nodejs child-process库来开子进程执行A

**Comment by sunpeng1996** [comment]
我想知道intel-iot-services-orchestration-layer如何与树莓派连接起来，谢谢

**Comment by jonathanding** [comment]
可以参照帮助文档中关于Edison的setup。只需要在树莓派上装上node.js，然后把iot-sol的代码放进去，然后运行start_mock_demo.sh就可以了。
这样的安装方式是把center, hub，broker都放到了树莓派上。

也可以有其他的安装方式，例如只是把hub安装树莓派上， 然后和在另外一个地方的center相连 - 只需要在树莓派的hub的config文件中配置正确broker的地址即可。
还可以在一个hub（不在树莓派上）中自己写一个service，和树莓派上运行的程序用用socket或者http等方式通信。

需要阅读帮助文档中的advanced那一块的内容来理解hub, center，broker的概念，以选择具体的部署方式

**Comment by sunpeng1996** [comment]
嗯嗯，我已经把iot装在树莓派上了，可是我并不知道如何把硬件连接到这个Services-o-layer上，比如，这个IOT-SOL平台如何感知我装了一个摄像头或者一个灯泡，它是怎么控制的，这个很朦胧，还希望大家讲解，谢谢。 @jonathanding @richardcypher @ruizeng @jiangzidong

**Comment by jonathanding** [comment]
事实上iot-sol并不负责感知这些。而是开发者需要开发对应的服务去控制摄像头和灯泡，这样的每一个控制程序是一个Service。iot-sol的主要作用是帮助完成这些service之间的协作，即orchestration。例如可以当一个motion sensor测到数据后去调用打开led的服务，等等。

当然，在此基础上，iot-sol内置了一些预先开发好的服务。这些服务有一类是不需要配置的，例如数学计算的服务等，有一类是需要配置的，最典型的就是和设备相关的。例如我们针对DFRobot的startkit内置了一些服务，这样如果使用里面的传感器的时候不要自己再去写服务了。但是事实上我们不知道你会把DFRobot的某个传感器物理连接到Edison/树莓派的哪个GPIO pin上。所以当使用这个传感器服务的时候你需要一下告诉它是哪个pin

更进一步的，由于这是一个开源项目，也可以未来会有contributor，针对某些类型的设备或者平台，把这个平台上的auto discovery的功能给集成进来，这样设备和配置都是自动感知自动完成的。

**Comment by Tommy-zhe** [comment]
我想问一下，官方提供的三种开发环境xdk,arduino和system studio如何跟iot-sol联系在一起，貌似功能重叠了,亦或是硬件连接开发单纯用iot-sol装在edison上就可以了？

**Comment by Tommy-zhe** [comment]
我想问一下，官方提供的三种开发环境xdk,arduino和system studio如何跟iot-sol联系在一起，貌似功能重叠了,亦或是硬件连接开发单纯用iot-sol装在edison上就可以了？ @jonathanding @jiangzidong

**Comment by jiangzidong** [comment]
@Tommy-zhe ， IoT SOL可以单独运行， 不需要其他SDK。在Edison上跑IoT SOL可以参照教程 [link](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/setup/edison_startkit)

**Comment by Tommy-zhe** [comment]
@jiangzidong ,非常感谢您的回答，但是我们在教程上并没有看到具体运行iot SOL的方法，因此我们尝试像访问usb那样访问运行，却被告知权限不足。后来我们又试着用screen登陆edison上运行IoT SOL，却找不到之前复制粘贴进去的IoT SOL文件。想请问一下是不是哪一步出错了。

**Comment by jiangzidong** [comment]
[这一页](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/setup/edison_startkit/3-Build IoT SOL)
基本流程是
1, 将SOL安装到Edison上 (Edison nodejs版本要求至少0.12).这个有很多方法, 比如在你host机器上 npm install iot-sol (host的nodejs版本要和edison一样), 然后将node_modules/iot-sol 文件夹复制到edison里. (如果直接在edison中npm install, 可能速度会比较慢). 复制的方法可以是scp, 或者sd卡, 等等
2, 进入edison console (ssh or uart), cd iot-sol, ./start_startkit.sh

不知道你具体是哪一步出了问题?

"因此我们尝试像访问usb那样访问运行", "找不到复制黏贴的文件", 我猜测, 你们是不是直接将文件放入Edison盘符? 这个并不能完成复制, 需要通过scp, 或者直接sd卡拷贝, 来完成文件的复制

**Comment by IceFireg** [comment]
@jiangzidong 刷新固件之后，为什么就找不到盘符了，之前没刷之前还找得到？

**Comment by jiangzidong** [comment]
@IceFireg 我没有遇到这样的问题. 你是否用这个方法来刷新固件? https://software.intel.com/en-us/get-started-edison-windows-step2

**Comment by Tommy-zhe** [comment]
@jiangzidong ，你好，最新我们在提高传感器的灵敏度，把传感器升级了，使用的dht22温湿度传感器要如何在iot-sol中一个pin扣值读取两个不同的数值（温度和湿度）呢？
![image](https://cloud.githubusercontent.com/assets/19224986/18497621/5d810688-7a62-11e6-9757-3b51d8444c82.png)

**Comment by jiangzidong** [comment]
@Tommy-zhe 我们并没有内置DHT传感器的service, 你需要自己实现.

DHT22 用了类似one-wire的传输方式, 而现有mraa/upm并不支持这种方式/设备, 所以实现js接口是有难度的. 你可以花时间研究一下.

在调式的时候, 先不用开启iotsol, 只要你能在nodejs下面成功操作dht22, 再将相关代码放入iotsol中.

**Comment by IceFireg** [comment]
@jiangzidong 
![2016-09-17 12-30-43](https://cloud.githubusercontent.com/assets/18031253/18605940/98145cb0-7cd2-11e6-8f9e-e4aa7dd416ec.png)
server我们写的是 tcp://mosquitto.org:1883
我们单独运行这一个服务，但是无法启动，是什么问题呢？

**Comment by jayjliang** [comment]
@IceFireg 你使用的是mqtt组件 server需要以mqtt开头 或者你直接写mosquitto.org:1883 因为service会自动帮你加的

**Comment by jiangzidong** [comment]
@IceFireg   我们测试的时候是自己搭建mqtt server的, 这里你用的mosquitto.org是一个公共server吗? 是不是test.mosquitto.org?
