### ISSUE TITLE
关于IOT 多线程问题

### ISSUE THREAD

**Issue by sunpeng1996** [01org/intel-iot-services-orchestration-layer#40]
您好，我在IOT中写的服务都是通过子进程调用的，会出现 子进程 还没执行完，该服务的output就输出了的情况，我该怎么让子进程执行完之后，服务再输出结果呢？谢谢。

**Comment by jiangzidong** [comment]
请参考 https://nodejs.org/api/child_process.html#child_process_event_exit

```
child=spawn(xxxxx)
child.on("exit", function(){
  sendOUT(xxxx)
})
```

**Comment by sunpeng1996** [comment]
好的，非常感谢您的回复！
