### ISSUE TITLE
Try to write a Widget into iot-dev,but...

### ISSUE THREAD

**Issue by qq332769043** [01org/intel-iot-services-orchestration-layer#48]
I want to write a Wideget into iot-dev.
As http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/add_widget_builtin
Step.1 create ui-widgets/widgets-jsx/xxx.js
Step.2 add spec to ui-widgets/specs.js
Step.3 add entry to ui-widgets/index.js
But something goes wrong:
![image](https://cloud.githubusercontent.com/assets/15059452/19597505/9dfc5e92-97c7-11e6-9e5f-6e141b5ed27c.png)
and all new-add-widget gets stuck and they are unresponsive.

So I use the Image Widget code(builtin) instead my code according to the 3 Step.
But bug still is bug.

Did I do something wrong?

And I also want to ask How to replace the "icon" of my widget in specs.js,where the picture should be?
Thank you.

**Comment by jiangzidong** [comment]
@qq332769043  I think the `add widget` operation is for dev branch. We need to modify the `ui-widget` folder in dev branch, then build by `build.sh` or `link-npms.sh`. I just suspect you directly operate in the master branch (or `dist` folder ), do you?

@jjykh Am i right about that?
If so, it is our mistake that we forget to mention that in the help doc.

**Comment by qq332769043** [comment]
where is the ui-widget folder in master branch

**Comment by jiangzidong** [comment]
both master and dev branch have a folder named ui-widgets. you should modify the dev's ui-widgets according to the doc, and then run ./build.sh. 
- then it will create a folder named "dist", cd dist, the dist's content is like master branch with your added new widget
- then in dist, run `npm install`
- start the iot sol, and see whether the new widget works well

**Comment by qq332769043** [comment]
@jiangzidong How to replace the "icon" of my widget in specs.js,where the picture should be?

**Comment by qq332769043** [comment]
@jiangzidong If I want to write into master branch,what should I do?

**Comment by IceFireg** [comment]
@jiangzidong 
我们在DFRobot上购买的IO扩展板（自带有能被iot-sol识别的传感器服务）经常会出现下一次使用就不能识别这些服务的问题，但用Intel_Edison_Setup_Lin_2016.2.002刷新固件后又能重新识别，十分不稳定，请问您知道是什么原因吗？该怎么解决呢？

**Comment by jiangzidong** [comment]
@qq332769043 it is complicated to add widgets directly in master branch for now. 

as for the icon issue, @jjykh will answer later.

**Comment by jiangzidong** [comment]
@IceFireg 没有遇到过这个情况， 请否描述一下“不能识别服务” 是什么现象，有么有重现的步骤。谢谢

**Comment by qq332769043** [comment]
@jjykh How to replace the "icon" of my widget in specs.js,where the picture should be?

**Comment by IceFireg** [comment]
@jiangzidong就像这样
![2016-10-23 14-59-47](https://cloud.githubusercontent.com/assets/18031253/19624616/9db38bb6-9931-11e6-94c0-aef5ce121719.png)
下图是它自带的服务
![2016-10-23 15-00-34](https://cloud.githubusercontent.com/assets/18031253/19624617/b590cb0e-9931-11e6-87a8-047881963d53.png)
如果不能识别，这些服务也看不到。如果重新run the setup tool，再把原来的iot-sol复制进去就又可以看到。

**Comment by jjykh** [comment]
@qq332769043 
In general, there are two ways to add new UI widget.
1. For dev branch, please refer to [UI Widget](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/basics/4-UI_Widget) for details.
   Examples & docs: 
- [Liquid Gauge Widget](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/add_widget)
- [Radio Widget](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/add_widget_builtin)
1. For master branch,  see also [Add UI Widget](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/add_widget)

**Comment by jjykh** [comment]
@qq332769043 

To change the icon of UI Widget, please refer to [Font Awesome Icon](http://fontawesome.io/icons/).
For example, the builtin _text_ widget using an icon 
![image](https://cloud.githubusercontent.com/assets/12082826/19633941/14e6b8cc-99e9-11e6-928c-490126ace5d7.png), its name is [text-width](http://fontawesome.io/icon/text-width/).

If the widget was created by iotsol IDE, you can click the icon on preview panel to select one icon for your widget.
![image](https://cloud.githubusercontent.com/assets/12082826/19634101/a0cbb986-99ea-11e6-955f-8a91949720b5.png)

**Comment by jiangzidong** [comment]
@IceFireg 不知道你能不能在出问题的时候, 给我发以下文件 (可以直接发我邮件 zidong.jiang@intel.com)
- node_modules/hope-center文件夹
- node_modules/hope-demo/center文件夹
- center.log
- startkithub.log

Thanks

**Comment by qq332769043** [comment]
@jjykh I try to add wideget into master branch as doc  but when I run"gulp build"
it show that"No gulpfile found ",the doc seems also is right to dev but not master.

**Comment by qq332769043** [comment]
@jiangzidong @jjykh  I insist on working on master branch because I dont know why there is so many error during setting up dev branch,some times it makes the whole IoT don't work and I must redo all.(Windows and Ubuntu)
Setting up dev branch takes me at least 2 hours and rebuild to test my widget takes me at least 40 minutes once,but I even don't know IoT could rework. I don't know what should I do.

**Comment by jjykh** [comment]
@qq332769043 
You should execute _gen_doc.sh_ under **doc** directory on master branch.

**Comment by jjykh** [comment]
@qq332769043 
Please refer to [Contribute to the Development Project](https://github.com/01org/intel-iot-services-orchestration-layer#contribute-to-the-development-project) for selection between **master** and **dev** branch.
The iotsol _dev_  branch, each sub-module(e.g base,center,workflow,ui-dev) depend on lots of third-party modules,  setting up is really a time-consuming process.
For _master_ branch, we merged third-party npm modules from all sub-module, and provided prebuilt ui-dev and ui-user.

**Comment by qq332769043** [comment]
@jjykh  where is gen_doc,sh in master branch

**Comment by qq332769043** [comment]
@jjykh I think you mean the doc is http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/add_widget
 but when I run"gulp build" to rebuild ui-widget it show that"No gulpfile found "

**Comment by jjykh** [comment]
Sorry, to update docs, please switch to _dev_ branch, _master_ branch didn't support to update docs.

**Comment by jjykh** [comment]
@qq332769043 
If you add new widget on _dev_ branch, you should run _gulp build_.
but if you are working on _master_ branch, you should put your codes under **ui-widgets/addons**, and needn't run building script.

**Comment by qq332769043** [comment]
@jjykh when I add my widget into ui-widgets/addons and start master branch, then I open"http://localhost:8080",the window of ide is blank at all with out no respose.
Is that because of using third-party react module?
How can I read debugging information of my widget.

**Comment by qq332769043** [comment]
@jjykh It seems that because of using third-party react module,why?

**Comment by qq332769043** [comment]
@jjykh why I can't use third-party react module,the window of ide is blank at all with no respose?

**Comment by IceFireg** [comment]
@jiangzidong 
恩，好的。如果下次出现问题，我把这几个文件发给你。

**Comment by qq332769043** [comment]
@jjykh this is my demo.jsx:
http://ofe3bo0re.bkt.clouddn.com/2.png
Is there any problems to make the window of ide to be blank at all with no respose?
qrcode.react:https://github.com/zpao/qrcode.react

**Comment by qq332769043** [comment]
@jjykh 。。。。。。

**Comment by jjykh** [comment]
@qq332769043 
If you are working on _master_ branch, you cannot require third-party npm module for widget. because the requiring procedure is  processed by [browserify](http://browserify.org/) in build script only on _dev_ branch. BTW, **React** was exported as global variable in iotsol, so you needn't require yourself. 

If you want to include third-party source code, you should copy the pure javascript code to your widget directory, iotsol will insert the javascript code in HTML.

I think you can try to add your widget into ui-widgets on _dev_ branch, then run _gulp build_ ui-widgets module, and ui-dev, ui-user.

**Comment by jjykh** [comment]
@qq332769043 
To add widget on _dev_ branch, please refer to [Liquid Gauge Widget](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/example/add_widget)

**Comment by qq332769043** [comment]
@jjykh but when I run "gulp build" it show that no gulpfile found

**Comment by jjykh** [comment]
@qq332769043 run _git checkout dev_ switch to _dev_ branch.

**Comment by qq332769043** [comment]
@jiangzidong @jjykh  Thank you.
