### ISSUE TITLE
关于添加一个i2c的iot服务

### ISSUE THREAD

**Issue by 2659494286** [01org/intel-iot-services-orchestration-layer#51]
我想添加一个I2c通信的服务，之前说的是我要仿照startkit或edison新建一个hub，建立hub之后再添加相关的md文档时是放在哪一个目录下呢，是在intel-iot-services-orchestration-layer/doc/md/下新建一个对应的文件夹么

**Comment by qq332769043** [comment]
@2659494286 你应该放在dev分支的center/lib/hubbundles/thingbundle/下的builtin hub中添加   doc/md/是放对应文档的地方

**Comment by jiangzidong** [comment]
首先, 都是对dev branch进行开发

如果是通用性的服务(与硬件平台无关), 应该放在center/lib/hubbundles/thingbundle/
如果是与平台相关的, 应该放在demo下的对应hub中, 或者新建一个hub
这里hub就是硬件平台的意思. 如果是Edison上的i2c相关的, 你可以放到demo/edison下

至于doc, 是在doc/md/对应hub下 (edison现在还没有hub, 你可以新建一个)

**Comment by 2659494286** [comment]
@jiangzidong 好的，我已经发起pull request了
