### ISSUE TITLE
关于图形界面的疑问

### ISSUE THREAD

**Issue by windmillknight** [01org/intel-iot-services-orchestration-layer#6]
您好，我是第九届英特尔杯软件创新大赛的一名参赛学生，大赛要用到您所开发的工具，但是我在linux按照步骤安装后，无法在localhost：8080中打开图形界面，请问我该怎么做。

**Comment by jiangzidong** [comment]
@windmillknight 你能提供更具体的信息吗？
1：nodejs版本和ubuntu版本 （or 其他linux发行版）
2：你的安装步骤是具体是这么样的 （执行了哪些命令）
3：请打开两个窗口，分别执行./run broker 和 ./run center  并贴出这些命令的log信息

**Comment by windmillknight** [comment]
您好，谢谢您能回复我的信息，我的 nodejs 版本是v4.4.3 ,系统是 ubuntu 14.04,安装步骤是按照readme中的步骤进行的,执行了
./dev-install.sh
./link-npms.sh
./build.sh nodoc
以下是我的截图
![2016-04-20 10 01 23](https://cloud.githubusercontent.com/assets/18244752/14661273/dc70875e-06de-11e6-83f7-9f5223a8d4e0.png)

![2016-04-20 09 59 26](https://cloud.githubusercontent.com/assets/18244752/14661240/b892a92a-06de-11e6-9eeb-64f4fa3fb916.png)

**Comment by jiangzidong** [comment]
1，运行./run broker 和 ./run center 时不要带& ， 让他们在前台运行， 请再贴图看看
2，如果你设置了代理， 确保no_proxy中有localhost 和 127.0.0.1

```
export no_proxy=localhost,127.0.0.1
```

**Comment by windmillknight** [comment]
您好，我现在出现了这个问题，请问是为什么呀？
![2016-04-20 11 00 11](https://cloud.githubusercontent.com/assets/18244752/14662326/8f70a8ea-06e7-11e6-8231-e8a5ac543196.png)
![2016-04-20 11 00 24](https://cloud.githubusercontent.com/assets/18244752/14662327/906487da-06e7-11e6-92a1-4b2984c8790d.png)

**Comment by jiangzidong** [comment]
1，运行./run broker 和 ./run center 时不要带& ， 让他们在前台运行， 请再贴出log
2，执行 `export | grep proxy`, 贴出输出信息

**Comment by windmillknight** [comment]
您好，我执行第一个的运行截图是这样的：
![2016-04-20 11 12 23](https://cloud.githubusercontent.com/assets/18244752/14662473/15c5ac1e-06e9-11e6-9685-be2e4661a139.png)
![2016-04-20 11 12 54](https://cloud.githubusercontent.com/assets/18244752/14662478/1bbf564c-06e9-11e6-8fef-4d2bb8f35ac1.png)
![2016-04-20 11 13 42](https://cloud.githubusercontent.com/assets/18244752/14662479/1f90b8f6-06e9-11e6-97bd-004b53dc843d.png)
![2016-04-20 11 13 59](https://cloud.githubusercontent.com/assets/18244752/14662481/222269d4-06e9-11e6-8e84-d1b10fa4579f.png)
然后并不能 执行 export | grep proxy

**Comment by jiangzidong** [comment]
1，listen EADDRINUSE 这个错误通常是因为之前的进程还在后台运行，请执行 `sudo killall node` 然后在试一次
2，为什么不能执行export。。。
3,  不一定要贴图，直接贴上输出信息即可

**Comment by windmillknight** [comment]
额，重启了一下就不会会报错了，但是仍然连接不上
![2016-04-20 11 29 34](https://cloud.githubusercontent.com/assets/18244752/14662704/5ed35dbe-06eb-11e6-956d-b08220f311c0.png)
![2016-04-20 11 29 59](https://cloud.githubusercontent.com/assets/18244752/14662706/61ab7256-06eb-11e6-9108-3f1a999adedf.png)
然后执行 export | grep proxy说命令没找到
![2016-04-20 11 30 13](https://cloud.githubusercontent.com/assets/18244752/14662714/71549494-06eb-11e6-9f0b-a7a471679fce.png)

**Comment by jonathanding** [comment]
export不需要在sudo下执行。

另外我们下午会有一个新的Release，该版本会简化安装避免自己build。另外会加入一些对proxy的检查。防止你本地设的proxy影响。

**Comment by windmillknight** [comment]
直接运行的话，就没有信息输出
![2016-04-20 11 30 13](https://cloud.githubusercontent.com/assets/18244752/14662806/5c60482a-06ec-11e6-87d5-18b209f9e3a6.png)
那我们就等您下午的版本么？

**Comment by windmillknight** [comment]
不好意思，才发现上一条贴错图了....
![2016-04-20 11 38 04](https://cloud.githubusercontent.com/assets/18244752/14666277/5532750e-070b-11e6-9671-499659104114.png)

**Comment by jonathanding** [comment]
你好，请试用刚刚上传的最新版本。注意安装方式有较大简化，请遵循新的安装使用方式

**Comment by windmillknight** [comment]
您好，实在不好意思，我们校园网出现了问题，所以现在才回复您。
新版本我已经运行成功了，多谢你们（感觉“您们”这个称呼好怪）的耐心回复，祝你们工作顺利 ！

**Comment by jonathanding** [comment]
不客气。欢迎多多试用并给出建议！
