### ISSUE TITLE
关于帮助文档的疑问

### ISSUE THREAD

**Issue by windmillknight** [01org/intel-iot-services-orchestration-layer#7]
您好，我又有问题想要请教您，帮助文档关于ui是这么说的
![2016-05-05 19-41-59](https://cloud.githubusercontent.com/assets/18244752/15042952/ee9c6b0a-12fa-11e6-8c22-eef30d4ff2a8.png)

但是在我本地的文件夹中并没有widgets-jsx这一项呀，请问这是为什么？
![2016-05-05 19-46-15](https://cloud.githubusercontent.com/assets/18244752/15042959/f9803664-12fa-11e6-981c-e08f22eef6f9.png)

**Comment by jonathanding** [comment]
你好！是这样子的，ui widget的开发是需要经过一个build的过程，即写好的JavaScript等文件最终会被处理再打包出来供使用。

所以git clone下载下来的最新版本会有几个branch。默认的是master branch，里面提供的已经build好的代码，可以直接运行，也可以在里面添加服务。

但是如果要添加ui widget的话，由于绕不开build这个过程，所以需要切换到dev branch （可以参考master branch里的README中关于contribute to development branch那一段），并按照dev branch里面的README（和master branch的README不一样）来setup整套的开发环境。在dev branch里面开发好了之后，需要执行build脚本来生成可以最终直接使用的版本（即类似于master branch的版本）。

多谢你指出这点。我们会在帮助文档中做进一步的澄清和说明。

**Comment by windmillknight** [comment]
谢谢您的回复，我已经搞懂了。：）

**Comment by jonathanding** [comment]
The latest version now allows to directly add widgets in release project without the need of building. Please check the latest version and its documentation for more details.
