### ISSUE TITLE
编辑workflow出错

### ISSUE THREAD

**Issue by yuansgit** [01org/intel-iot-services-orchestration-layer#8]
我刚接触iot-sol,在linux上安装部署成功iot-sol后，按照在线文档中的步骤操作时，在edit workflow时不能把控件拖到界面上，上面提示这样的错误信息：Failed to show the workflow because t.setLineDash is not a function。

**Comment by jonathanding** [comment]
你好，我在Ubuntu LTS 14.04上无法重现该问题。请问你使用的浏览器及其版本？

从错误信息上看，可能是浏览器比较旧，不支持HTML5当中的Canvas中的setLineDash API.

例如，IE10就未能加入该支持。https://social.msdn.microsoft.com/Forums/en-US/85007e72-90ad-4bd9-affd-9a24702219e6/canvasrenderingcontext2dsetlinedash-and-linedashoffset-missing?forum=winappswithhtml5

**Comment by yuansgit** [comment]
我升级了下浏览器，可以了，谢谢
