### ISSUE TITLE
关于硬件选择的问题

### ISSUE THREAD

**Issue by windmillknight** [01org/intel-iot-services-orchestration-layer#9]
您好，请问现在这个平台只支持DFRobot Starter Kit for Intel® Edison/Galileo和Intel® Edison with Arduino Breakout Kit扩展板么？还是官网上介绍的几款套件都支持？

**Comment by jiangzidong** [comment]
你好, IoT SOL本身是一个物联网应用开发平台, 与底层硬件无关, 只要能跑nodejs的,就可以跑SOL.

对于http://01org.github.io/intel-iot-services-orchestration-layer/ 左边"setup"中列出的硬件+OS组合, 我们另外提供了相关service,可以让开发者直接调用. 其他的组合,需要开发者自己提供service.

开发service的教程在 http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service

请问你想在哪个套件上开发

**Comment by windmillknight** [comment]
您好，我们准备用edison的Break board或者用sparkfun的套件或者可穿戴的那个套件，还不知道选择哪一种，因为都不是很清楚到底怎么用。另外想问一下，是不是只要把io线和其他传感器连接起来，就可以实现控制了? 还是需要其他条件？

**Comment by jiangzidong** [comment]
你需要

1)可以用javascript 控制io/传感器, 比如借助mraa or johnny-five. 将它包装为IoT SOL service
[link](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service/4-direct service)

或者

2)已经有一个二进制程序, 可以控制io/sensor, 那么利用nodejs的child-process module, 将它包装为一个IoT SOL service
[link](http://01org.github.io/intel-iot-services-orchestration-layer/#getstarted/advanced/edit_service/5-service with binary)

**Comment by windmillknight** [comment]
好的，我明白了，谢谢您~
